#!/bin/sh
lock() {
	i3lock -d -i /home/rdg/Pictures/backgrounds/nature/artistic.png -c 000000
}

case "$1" in
    lock)
        lock && xset dpms force off
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
	logger Suspending from i3
        lock && sudo pm-suspend
        ;;
    hibernate)
	logger Hibernating from i3
        lock && sudo pm-hibernate
        ;;
    reboot)
        sudo shutdown now -r
        ;;
    shutdown)
        sudo shutdown now -h
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
